cc_library(
    name = "assfire_optimizer_cc_api",
    srcs = ["OptimizerApi.cpp"],
    hdrs = [
        "assfire/optimizer/api/GeoPoint.hpp",
        "assfire/optimizer/api/Order.hpp",
        "assfire/optimizer/api/RouteOptimizer.hpp",
        "assfire/optimizer/api/Session.hpp",
        "assfire/optimizer/api/Solution.hpp",
        "assfire/optimizer/api/Task.hpp",
        "assfire/optimizer/api/TimeWindow.hpp",
    ],
    deps = ["@com_google_absl//absl/time"],
)
