cc_library(
    name = "assfire_optimizer_cc_engine",
    srcs = [
        "assfire/optimizer/engine/OptimizationStrategyProvider.cpp",
        "assfire/optimizer/engine/RouteOptimizerEngine.cpp",
    ],
    hdrs = [
        "assfire/optimizer/engine/OptimizationStrategyProvider.hpp",
        "assfire/optimizer/engine/RouteOptimizerEngine.hpp",
    ],
    deps = ["//api/cpp:assfire_optimizer_cc_api"],
)
